name: storybook
description: Package to visualize components and design tokens.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  design_system:
    path: ../design_system
  flutter:
    sdk: flutter
  storybook_flutter: ^0.11.2+2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true