name: profile
description: OPX Profile Module
version: 1.1.0
publish_to: none
homepage: https://grupoq.io/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  authentication:
    git:
      url: https://github.com/qcx/chimera.git
      ref: authentication-v2.0.0
      path: authentication
  core:
    git:
      url: https://github.com/qcx/chimera.git
      ref: core-v2.0.0
      path: core
  certificates:
    git:
      url: https://github.com/qcx/chimera.git
      ref: certificates-v1.0.6
      path: commons/certificates   
  learning:
    git:
      url: https://github.com/qcx/chimera.git
      ref: learning-v1.0.2
      path: commons/learning
  dependencies:
    git:
      url: https://github.com/qcx/chimera.git
      ref: dependencies-v2.0.0
      path: commons/dependencies
  design_system:
    git:
      url: https://github.com/qcx/chimera.git
      ref: design_system-v2.0.0
      path: design_system
  flutter:
    sdk: flutter
  iterable:
    git:
      url: https://github.com/qcx/chimera.git
      ref: iterable-v1.2.0
      path: commons/iterable
  storage:
    git:
      url: https://github.com/qcx/chimera.git
      ref: storage-v1.1.0
      path: commons/storage
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test:

flutter: