name: core
description: Micro-app core.
version: 2.0.0
publish_to: none
homepage: https://grupoq.io/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  dependencies:
    git:
      url: https://github.com/qcx/chimera.git
      ref: dependencies-v2.0.0
      path: commons/dependencies
  configuration:
    git:
      url: https://github.com/qcx/chimera.git
      ref: configuration-v1.1.0
      path: commons/configuration
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
