name: checkout
description: Checkout
version: 1.1.0
homepage: https://grupoq.io/
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    git:
      url: https://github.com/qcx/chimera.git
      ref: core-v2.0.0
      path: core
  authentication:
    git:
      url: https://github.com/qcx/chimera.git
      ref: authentication-v2.0.0
      path: authentication    
  discovery:
    git:
      url: https://github.com/qcx/chimera.git
      ref: discovery-v1.1.0
      path: discovery    
  dependencies:
    git:
      url: https://github.com/qcx/chimera.git
      ref: dependencies-v2.0.0
      path: commons/dependencies
  design_system:
    git:
      url: https://github.com/qcx/chimera.git
      ref: design_system-v2.0.0
      path: design_system
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0