name: design_system
description: OPX Design System
version: 2.0.0
homepage: https://grupoq.io/
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Default cache network image throws exceptions when load images is fall
  cached_network_image:
    git:
      url: "https://github.com/kaiquegazola/flutter_cached_network_image"
      ref: 9122f5c7cb4daee67989c5759156b9099b60e1f0
      path: "cached_network_image"
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_styled_toast: 2.1.3
  flutter_svg: ^1.1.6
  flutter_widget_from_html_core: ^0.9.0+2
  infinite_scroll_pagination: ^3.2.0
  lottie: ^2.0.0
  percent_indicator: ^4.2.2
  webview_flutter: ^3.0.4
  core:
    git:
      url: https://github.com/qcx/chimera.git
      ref: core-v2.0.0
      path: core
  dynamic_height_grid_view: ^0.0.3
  internationalization:
    git:
      url: https://github.com/qcx/chimera.git
      ref: internationalization-v1.1.0
      path: commons/internationalization
  generic_exception:
    git:
      url: https://github.com/qcx/chimera.git
      ref: generic_exception-v1.0.6
      path: commons/generic_exception    
  flutter_inappwebview: ^6.0.0-beta.22
  styled_text: ^6.0.0
  pdf_render: ^1.3.8
  flutter_cache_manager: ^3.3.0
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: Krub
      fonts:
        - asset: assets/fonts/krub/Krub-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/krub/Krub-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/krub/Krub-Light.ttf
          weight: 300
        - asset: assets/fonts/krub/Krub-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/krub/Krub-Regular.ttf
          weight: 400
        - asset: assets/fonts/krub/Krub-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/krub/Krub-Medium.ttf
          weight: 500
        - asset: assets/fonts/krub/Krub-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/krub/Krub-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/krub/Krub-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/krub/Krub-Bold.ttf
          weight: 700
        - asset: assets/fonts/krub/Krub-BoldItalic.ttf
          weight: 700
          style: italic