abstract class Discovery {
  String cashPrice(int value, String iso);
  String contentExpectationDescription(int hours);
  String get addToCart;
  String get buyAdvantageDescription01;
  String get buyAdvantageDescription02;
  String get buyAdvantageDescription03;
  String get buyAdvantageDescription04;
  String get buyAdvantageTitle01;
  String get buyAdvantageTitle02;
  String get buyAdvantageTitle03;
  String get buyAdvantageTitle04;
  String get buyCourse;
  String get buyCourseAdvantages;
  String get categories;
  String get courseCertificateSign;
  String get courseDeviceCompatibility;
  String get courseExpectationsTitle;
  String get discovery;
  String get goalsTitle;
  String get institutionalCertificate;
  String get likedCourses;
  String get mostPurchased;
  String get mostSearched;
  String get mostSearchedCourses;
  String get navigateByCategory;
  String get oneYearAccess;
  String get online;
  String get recentSearches;
  String get recentViewed;
  String get search;
  String get searchACourse;
  String get searchEmptyStateSubtitle;
  String get searchEmptyStateTitle;
  String get seeAll;
  String get seeAllLiked;
  String get seeAllMostSearched;
  String get seeAllRecentViewed;
  String get seeCourseContent;
  String get seeLess;
  String get seeMore;
  String get suggestionsForYou;
  String get topSearches;
  String get whoBoughtAlsoView;
  String installmentsPrice(int maxInstallments, int value, String iso);
  String price(int value, String iso);
  String seeAllCategory(String categoryName);
}
