name: authentication
description: OPX Login module.
version: 2.0.0
publish_to: none
homepage: https://grupoq.io/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  core:
    git:
      url: https://github.com/qcx/chimera.git
      ref: core-v2.0.0
      path: core
  crypto: ^3.0.2
  dependencies:
    git:
      url: https://github.com/qcx/chimera.git
      ref: dependencies-v2.0.0
      path: commons/dependencies
  design_system:
    git:
      url: https://github.com/qcx/chimera.git
      ref: design_system-v2.0.0
      path: design_system
  flutter:
    sdk: flutter
  iterable:
    git:
      url: https://github.com/qcx/chimera.git
      ref: iterable-v1.2.0
      path: commons/iterable
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
  storage:
    git:
      url: https://github.com/qcx/chimera.git
      ref: storage-v1.1.0
      path: commons/storage    

dev_dependencies:
  faker:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test:

flutter: